apiVersion: v1
kind: Service
metadata:
  name: peer-zone-a
  namespace: parking-fabric
  labels:
    app: fabric-peer
    zone: zone-a
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 7051
    targetPort: 7051
    name: grpc
  - port: 9443
    targetPort: 9443
    name: operations
  selector:
    app: fabric-peer
    zone: zone-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer-zone-a
  namespace: parking-fabric
  labels:
    app: fabric-peer
    zone: zone-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-peer
      zone: zone-a
  template:
    metadata:
      labels:
        app: fabric-peer
        zone: zone-a
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9443"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
      - name: copy-materials
        image: busybox:1.35
        command: ['sh', '-c']
        args:
          - |
            mkdir -p /var/hyperledger/peer-data/msp/admincerts /var/hyperledger/peer-data/msp/cacerts /var/hyperledger/peer-data/msp/keystore /var/hyperledger/peer-data/msp/signcerts /var/hyperledger/peer-data/msp/tlscacerts /var/hyperledger/peer-data/tls /var/hyperledger/peer-data/production
            cp -Lrv /msp-ro/admincert.pem /var/hyperledger/peer-data/msp/admincerts/
            cp -Lrv /msp-ro/cacert.pem /var/hyperledger/peer-data/msp/cacerts/
            mv /var/hyperledger/peer-data/msp/cacerts/cacert.pem /var/hyperledger/peer-data/msp/cacerts/ca.zone-a.parking.com-cert.pem
            cp -Lrv /msp-ro/tlscacert.pem /var/hyperledger/peer-data/msp/tlscacerts/
            cp -Lrv /msp-ro/config.yaml /var/hyperledger/peer-data/msp/config.yaml
            cp -Lrv /msp-ro/keystore.pem /var/hyperledger/peer-data/msp/keystore/
            cp -Lrv /msp-ro/signcert.pem /var/hyperledger/peer-data/msp/signcerts/
            cp -Lrv /tls-ro/* /var/hyperledger/peer-data/tls/
        volumeMounts:
        - name: zone-a-msp-secret
          mountPath: /msp-ro
        - name: zone-a-tls-secret
          mountPath: /tls-ro
        - name: peer-data-volume
          mountPath: /var/hyperledger/peer-data
      containers:
      - name: peer
        image: hyperledger/fabric-peer:2.5
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "$ORDERER1_SERVICE_HOST orderer1.parking.com" >> /etc/hosts
            peer node start
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CORE_PEER_ID
          value: $(POD_NAME)
        - name: CORE_PEER_ADDRESS
          value: "peer-zone-a:7051"
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:7051"
        - name: CORE_PEER_CHAINCODEADDRESS
          value: "$(MY_POD_IP):7052"
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: "0.0.0.0:7052"
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: "peer-zone-a:7051"
        - name: CORE_PEER_LOCALMSPID
          value: "ZoneAMSP"
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/var/hyperledger/peer-data/msp"
        
        # --- ENABLE TLS (Untuk Komunikasi Antar Peer) ---
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/var/hyperledger/peer-data/tls/server.crt"
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/var/hyperledger/peer-data/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/var/hyperledger/peer-data/tls/ca.crt"
        
        # --- METRICS CONFIG (PERBAIKAN DISINI) ---
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "goleveldb"
        - name: CORE_OPERATIONS_LISTENADDRESS
          value: "0.0.0.0:9443"
        - name: CORE_METRICS_PROVIDER
          value: "prometheus"
        # MATIKAN TLS UNTUK OPERATIONS AGAR PROMETHEUS BISA BACA
        - name: CORE_OPERATIONS_TLS_ENABLED
          value: "false" 
          
        - name: FABRIC_LOGGING_SPEC
          value: "INFO"
        - name: CORE_VM_ENDPOINT
          value: "unix:///var/run/docker.sock"
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
          value: "parking-fabric"
        ports:
        - containerPort: 7051
          name: grpc
        - containerPort: 9443
          name: operations
        readinessProbe:
          tcpSocket:
            port: 7051
          initialDelaySeconds: 45
          periodSeconds: 5
        volumeMounts:
        - name: peer-data-volume
          mountPath: /var/hyperledger/peer-data/msp
          subPath: msp
        - name: peer-data-volume
          mountPath: /var/hyperledger/peer-data/tls
          subPath: tls
        - name: peer-data-volume
          mountPath: /var/hyperledger/production
          subPath: production
        - name: docker-sock
          mountPath: /var/run/docker.sock
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      volumes:
      - name: zone-a-msp-secret
        secret:
          secretName: zone-a-msp
      - name: zone-a-tls-secret
        secret:
          secretName: zone-a-tls
      - name: peer-data-volume
        emptyDir: {}
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock